server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: '/api'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gallery
    username: root
    password: 3161

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: gallerybackartbackend123354365464fdsagfdsgfdaggfdagd54352432543254325gdfdsgfdsgfdsgfds
  accessTokenValidationSecond: 1800000
  refreshTokenValidationSecond: 12960000


springdoc:
  version: v1
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /api/**