
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gallery
    username: root
    password: 3161

  jpa:
    open-in-view: false

jwt:
  secret: gallerybackartbackend123354365464fdsagfdsgfdaggfdagd54352432543254325gdfdsgfdsgfdsgfds